### ISSUE TITLE
Unauthorized when using admin key

### ISSUE THREAD

**Issue by JWambaugh** [fauna/vscode#108]
I'm new to fauna and trying to set up the vscode extension. I created an admin key, but no matter if i put it in `.faunarc` or in the extension settings, I get 'Unauthorized' messages like `Fetch Collections failed: unauthorized`.
I've tried recreating new keys, etc. to no avail. Is the extension broken?

**Comment by henryfauna** [comment]
Hi @JWambaugh! What region is your database in? If it's in a region other than `Classic` you'll need to update the `Domain` config in your VS Code settings as well. Databases in the `US` region group will need to use `db.us.fauna.com` and databases in the `EU` region group will need to use `db.eu.fauna.com`. You should be able to find more info [here](https://docs.fauna.com/fauna/current/learn/understanding/region_groups#how-to-use-region-groups).

**Comment by cleve-fauna** [comment]
Hey @JWambaugh,

I'm going to resolve this for now. Please reopen if you need further assistance!
