### ISSUE TITLE
Documents is not defined

### ISSUE THREAD

**Issue by jfloresremar** [fauna/vscode#12]
I've learned reading FaunaDB Docs and use frequently Documents function. 
When running a query the result message is Documents is not defined

`Map(
  Paginate(
    Documents(Collection("usuarios"))
  ),
  Lambda('usuario',
    {
      correo: Select(['data','correo'],Get(Var('usuario'))),
    }
  )
)
`
Thank you.
This query runs correctly using Fauna Shell

**Comment by BrunoQuaresma** [comment]
Working in progress...

**Comment by BrunoQuaresma** [comment]
It is on the 1.2.0 version.
