### ISSUE TITLE
Release tags would make it easier to follow the repo

### ISSUE THREAD

**Issue by vasco3** [fauna/vscode#28]
As an external viewer, would be less noisy for me to get notified only when there is a release, instead of looking at all the issues and merges.

**Comment by BrunoQuaresma** [comment]
I think you can manage your settings to receive less notifications from this repo, right? Or there is something in our side that we can do?

**Comment by vasco3** [comment]
hey @BrunoQuaresma what I mean is that I have to set to 
![image](https://user-images.githubusercontent.com/804301/78949011-d8892500-7a8f-11ea-9368-8e33ba86b18d.png)
instead of 
![image](https://user-images.githubusercontent.com/804301/78949027-e3dc5080-7a8f-11ea-8b6b-b4846ffbe011.png)

in order to be aware when a new release is out. I don't check slack that often, so it would be great if this project would use release tags.

**Comment by BrunoQuaresma** [comment]
Ahh ok, I gotcha. @ryancharris @fauna-rodrigo @danieltodonnell, thoughts?

**Comment by fauna-rodrigo** [comment]
@BrunoQuaresma @ryancharris  We should apply our regular release/changelog management (as we do for console) to this repository too. what do you think?

**Comment by BrunoQuaresma** [comment]
@fauna-rodrigo I think that would be great. Also, would be great to have tags generated together with releases.

**Comment by BrunoQuaresma** [comment]
thanks @vasco3 we still working on this.
