### ISSUE TITLE
Bug: `fetch` is not defined GraphQL upload

### ISSUE THREAD

**Issue by mirshko** [fauna/vscode#31]
<img width="327" alt="Screen Shot 2020-04-19 at 10 28 23" src="https://user-images.githubusercontent.com/8116716/79683184-80d58100-8228-11ea-95b8-389cf0b71853.png">

I'm getting this error when trying to upload my schema using the VS Code extension.

Not sure if its on my end? 

ENV
- Node: 13.80,
- macOS: 10.15.4 (19E287)
- VS Code: 1.44.2

**Comment by BrunoQuaresma** [comment]
Thanks @mirshko for let us know. Internally tracked as FE-515.

**Comment by rahulkgupta** [comment]
Any update here? I just installed the VSCode plugin and received this error. I'm very excited to take advantage of the VS Code plugin!

**Comment by BrunoQuaresma** [comment]
Fixed on
