### ISSUE TITLE
Exists return empty object when ref not exist.

### ISSUE THREAD

**Issue by moreta** [fauna/vscode#33]
`Exists(Match(Index("unique_user_by_email"), "notexist@example.com"))`

From this query,

Fauna shell return false.
But vscode extension return empty object.
[faunadb-js](https://github.com/fauna/faunadb-js) also return boolean.
So I think this vscode issue.

![image](https://user-images.githubusercontent.com/115768/82464385-fcad3c80-9af8-11ea-8e3d-658c4f5b8629.png)

**Comment by BrunoQuaresma** [comment]
Thanks @moreta for let us now. This is internally tracked as FE-609

**Comment by fauna-ryanharris** [comment]
@moreta Thanks for bringing this to our attention -- I added a fix for this issue in #39, so I am going to close this issue 🙏
