### ISSUE TITLE
Allow setting fauna endpoint

### ISSUE THREAD

**Issue by exul** [fauna/vscode#42]
There doesn't seem to be an option to set the fauna endpoint when using the extension. During development it could be useful to set the fauna endpoint to `http://localhost:8443` when working with the docker image.

**Comment by danieltodonnell** [comment]
Sorry for the delay on replying to this.  We will look into it and get back to you.  

Dan

**Comment by ryancharris** [comment]
@exul Good idea! I will create an internal ticket for this and have our product team prioritize it. Thanks for the suggestion 🙏

**Comment by aleclarson** [comment]
Fixed by #52
