### ISSUE TITLE
Outlined Icon

### ISSUE THREAD

**Issue by baldwin-design-co** [fauna/vscode#43]
The icons on the sidebar of vscode are all outlined and the fauna extension would feel much more at home if it's logo was as well.

**Comment by danieltodonnell** [comment]
This seems like a valid point.  @baldwin-design-co  can you paste a screen capture of how it looks in your vscode so we can confirm we're seeing the same thing?

**Comment by baldwin-design-co** [comment]
this is what it looks like now
![faunadb-issue-before](https://user-images.githubusercontent.com/67534814/97153057-1e0cf700-172f-11eb-9ce7-00bc8656a927.jpg)

and this is the improved version
![faunadb-issue-after](https://user-images.githubusercontent.com/67534814/97153121-3715a800-172f-11eb-83d7-58ff762da6c1.jpg)

**Comment by danieltodonnell** [comment]
@baldwin-design-co What you've mocked/made there look fantastic!  If you wanted to issue a PR with that file change in it, we'd be happy to accept it and send you some swag for it?

If that's more work than you wanted to do then i totally understand and we can reproduce your clear example. :D

**Comment by baldwin-design-co** [comment]
yep, just submitted a PR with the updated logo

**Comment by danieltodonnell** [comment]
Hi Ben,  Can you send me an email to `dan.odonnell@fauna.com` and I'll send you a code for some Fauna swag!

**Comment by baldwin-design-co** [comment]
Sent!
