### ISSUE TITLE
Can't work with child databases?

### ISSUE THREAD

**Issue by JerryGreen** [fauna/vscode#45]
Honestly I still don't quite get the sense of child databases, but it's still there, and it's also supported by https://github.com/fauna/fauna-shell, but within this VSCode extension I can't upload schema to child databases, it seems

**Comment by fireridlle** [comment]
Hello @JerryGreen. Sorry for the long response.

Child databases are visible on the left sidebar.
For uploading graphql schema you can change secret to child db secret
