### ISSUE TITLE
Line breaks = "Unexpected end of input"

### ISSUE THREAD

**Issue by charlie17** [fauna/vscode#47]
Took a minute to see what was causing it, but seems whenever there are line breaks in the .fql file (whether saving it as such or not), the output returns `ERROR: Unexpected end of input`. But collapsing the query down into one line and running it works every time. 

Bottom line, a query that is formatted and runs fine in the Shell will fail to run in the VS Code extension

**Comment by fireridlle** [comment]
Hello @charlie17. sorry for the late respone. The issue has been fixed https://github.com/fauna/vscode/pull/57. fresh version now at marketplace
