### ISSUE TITLE
Cannot find vscode extension via marketplace on Linux v1.52.1

### ISSUE THREAD

**Issue by chrische** [fauna/vscode#55]
I cannot find the vscode extension via the built in market place. Am I missing something? - Thanks in advance. :) 

### What steps were taken?
I tried to install the extension via the internal market place, as suggested in the [README](https://github.com/fauna/vscode/blob/1.6.0/README.md#getting-started). 

Search was done 
* via CTRL+P combination and inserting _ext install fauna.faunadb_
* via the search input field

### What are the expectations?
A search in Visual Studio Code shows the FaunaDB extension and allows me to install the extension.

### What was the actual result?
Executing a search has not shown an entry for _FaunaDB_, as you may see in the [attached screenshot](https://user-images.githubusercontent.com/3012147/103141184-092def00-46f1-11eb-99cb-6755e527eb23.jpg):

![fauna-exstension-screenshot-non-working](https://user-images.githubusercontent.com/3012147/103141184-092def00-46f1-11eb-99cb-6755e527eb23.jpg)

### Is there a workaround?
1. Use the [gallery web interface](https://marketplace.visualstudio.com/items?itemName=fauna.faunadb).
2. Download the VSIX file.
3. Import and install manually in Visual Studio Code.

### Additional info
The following system and code setup is used.

> Version: 1.52.1
> Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
> Date: 2020-12-19T14:42:39.893Z
> Electron: 9.4.0
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Linux x64 5.9.14-arch1-1

**Comment by wommy** [comment]
having the same problem

**Comment by fireridlle** [comment]
@chrische, @wommy just type `fauna`

**Comment by chrische** [comment]
@fireridlle, thanks for getting back. I also tried ``fauna`` when I opened this issue, and just retried it with the same result, as you may see in the attached screenshot. The steps I described above were just taken from the official marketplace, as well as your readme.

![image](https://user-images.githubusercontent.com/3012147/107208117-6f50a600-6a01-11eb-8f15-4808cf87099d.png)


Furthermore, I think, searches such as ``database`` might as well be good ones to come up with Fauna's extension:
![image](https://user-images.githubusercontent.com/3012147/107208069-5d6f0300-6a01-11eb-8271-411106f52e8d.png)


My system setup is almost the same, only ArchLinux and Electron got updated.
> Version: 1.52.1
> Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
> Date: 2020-12-19T14:42:39.893Z
> Electron: 9.4.2
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Linux x64 5.10.12-arch1-1

**Comment by chrische** [comment]
Spending a bit more time on debugging the issue, I came up with the following findings.

It looks like _code_ sends the following request when performing a search for extensions. As the following excerpt shows, it seems like the request is sent to ``open-vsx.org``. That's the point I expected it to be Microsoft's marketplace.
```
POST /vscode/gallery/extensionquery HTTP/1.1
Host: open-vsx.org
Connection: keep-alive
Content-Length: 232
X-Market-User-Id: x-x-x
Accept: application/json;api-version=3.0-preview.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) code-oss/1.52.1 Chrome/83.0.4103.122 Electron/9.4.2 Safari/537.36
X-Market-Client-Id: VSCode 1.52.1
Content-Type: application/json
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: de
Cookie: xxx
```

[Open VSX's about page](https://open-vsx.org/about) states the following:

> 
> Open VSX is an open-source registry for VS Code extensions. It can be used by any development environment that supports such extensions. See this article for more information.
> 
> This service is operated by the Eclipse Foundation.
> 
> The source code of Open VSX is managed by the Eclipse Open VSX project and is licensed under the Eclipse Public License v2.0. 

Diving a bit deeper into ArchLinux's ``code`` package information on the wiki, I also came up with [FS#67780](https://bugs.archlinux.org/task/67780). It describes how using Microsoft's store may be breaking their ToS. More information on that may as well be found in [Microsoft's description of Differences between the repository and Microsoft Visual Studio Code](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code) on microsoft/vscode.

# Is there a workaround?

* The [same as described above](https://github.com/fauna/vscode/issues/55#issue-774778410).
* Following the [comment in issue VSCodium/vscodium/418](https://github.com/VSCodium/vscodium/issues/418#issuecomment-643664182), by setting the URL manually in `product.json`. However, this may break Microsoft's ToS, as described above and in ArchLinux's bugtracker.


# How to resolve it in long-term?
Open VSX's process for publishing extensions [may be found here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension). Furthermore, there is [a GitHub action available](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#github-action).

@fireridlle, I would love to see the FaunaDB extension being published there. What do you think? 

In case you need more information or want me to publish it, I'd be happy to help, as well as contribute to the publishing process.

**Comment by wommy** [comment]
ok so the default community edition of arch's vscode doesnt have the microsoft store hooked in because of ToS, so i can download from the aur either the microsoft spin with the market cooked in, or the codium spin and edit some json, which is against the ToS

**Comment by chrische** [comment]
> is there an easy way to backup my settings before i flip bins, because i assume thats going to wipe everything

According to the configuration section, they use [different directories for configuration](https://wiki.archlinux.org/index.php/Visual_Studio_Code#Configuration). I can confirm the directory for the community ``code`` version. You may as well back up either directory before applying changes.

**Comment by rugk** [comment]
Note you can also submit your extension to the open VSX store:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by parkhomenko** [comment]
@chrische @wommy could you try again to search for **fauna** extension in vscode if you see a "1.8.1" version?

**Comment by wommy** [comment]
@parkhomenko

i got it working months ago with [vscodium bin marketplace](https://aur.archlinux.org/packages/vscodium-bin-marketplace/)

**Comment by parkhomenko** [comment]
thanks, @wommy, I'll close the issue for now, but feel free to write again if you find any other issues
