### ISSUE TITLE
"unauthorized" at fauna-dev (docker)

### ISSUE THREAD

**Issue by YanDevDe** [fauna/vscode#73]
Hello everyone!

I've been trying to use this extension under fauna-dev (which runs per docker). Hence I'm using .faunarc at my root project directory with empty global admin key.

I've tried following content:

```
FAUNA_KEY=secret
FAUNA_DOMAIN=127.0.0.1
FAUNA_SCHEME=http
FAUNA_PORT=8443
FAUNA_GRAPHQL_HOST=http://localhost:8084/graphql
```

But when trying to run this, all I get is "unauthorized" notification popup. This config works fine on `fauna-schema-migration` and `faunadb` nodejs module.

Am I missing something here?

Been running fauna's docker by:

```bash
docker run --rm --name faunadb -p 8443:8443 -p 8084:8084 fauna/faunadb
```

Any tips or help are welcome! :)

Thanks,

Yan

**Comment by YanDevDe** [comment]
Using 1.7.1 instead of 1.6.0 fixed the issue. Is there a way to disable / remove the 1.6.0 version one? I thought this was official one because it has more downloads and rating:

![image](https://user-images.githubusercontent.com/1526048/119243414-cc163d80-bb66-11eb-83e2-ed5d3d29ff52.png)

**Comment by fireridlle** [comment]
both of them are official. we have re-branding from FaunaDB to Fauna
