### ISSUE TITLE
Issue running multiline FQL queries

### ISSUE THREAD

**Issue by darryloctoberdgtls** [fauna/vscode#75]
Hi guys, nice VSCode plugin. Unfortunately I ran into a fairly major problem, which for me renders the entire plugin useless.

When I have an FQL file with a query on more than 1 line, I get an error like this:
"Unexpected end of input".

For example:
THIS WORKS:
Command palette: Cmd + Shift + P -> "FaunaDB: Run Query" command.

```
Paginate(Collections())
```

DOES NOT WORK:

```
Update(
  Ref(Collection("mycollection"), "287353998776759815"),
  {
    data: {
      id: 49,
      title: "NEW TITLE"
    }
  }
)
```
->
ERROR:
Unexpected end of input

I ran into this last year and was hoping that it might be fixed by now, maybe someone else pointed it out...?

**Comment by fireridlle** [comment]
Hi @darryloctoberdgtls. This issue has been fixed with this PR https://github.com/fauna/vscode/pull/57.
Update the plugin, please
